### ISSUE TITLE
【Molle UI追加機能】Moduleのディープコピー

### ISSUE THREAD

**Issue by chitose87** [chitose87/molle-cms--dev#20]
molle/ui/FocusExtension.vueにCopy機能を追加
新しいIDでitemDataをコピー
しかし、Boxなどのchildrenタイプの場合は子要素まで同様にコピーを回帰したい（ディープコピー

**Comment by aokiji516** [comment]
ひとまずディープコピーできるようになった。以下のペンディングあり。
・ログの作成は実装していないため、ログ機能の作り直しが終わったらログの作成を追加する
・cardなどカスタムモジュールのコピーはできない状態（valueの中身が固有なので一律の実装ができなかったため今はコピー不可にしてある）

**Comment by aokiji516** [comment]
対応完了しているのでクローズ
